# Use uma imagem Node.js oficial como a base
FROM node:16

# Define o diretório de trabalho dentro do contêiner
WORKDIR /app

# Copia os arquivos package.json e package-lock.json da pasta api
COPY ./api/package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do backend para o diretório de trabalho
COPY ./api ./

# Expõe a porta que o backend vai usar
EXPOSE 4000

# Comando para iniciar a aplicação
CMD ["node", "index.js"]
