# Usa a imagem oficial do Nginx
FROM nginx:alpine

# Remove a configuração padrão do Nginx
RUN rm /etc/nginx/conf.d/default.conf

# Copia a configuração personalizada para o diretório do Nginx
COPY nginx.conf /etc/nginx/conf.d

# Expõe a porta 80
EXPOSE 80
